config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries do
    resources :words
  end
  root :to => redirect('/dictionaries')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  validates :name, :language, :presence => true
  validates :name, :uniqueness => true

  has_many :words
end

app/models/word.rb
class Word < ApplicationRecord
  validates :name, :language, :definition, :presence => true
  belongs_to :dictionary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:name, :language)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    dictionary = Dictionary.find(params[:dictionary_id])
    @words = dictionary.words
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    dictionary = Dictionary.find(params[:dictionary_id])
    @word = dictionary.words.build
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    dictionary = Dictionary.find(params[:dictionary_id])
    @word = dictionary.words.create(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to [@word.dictionary, @word], notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: [@word.dictionary,  @word] } #this may be wrong; need to check
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to [@word.dictionary, @word], notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: [@word.dictionary, @word] }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to dictionary_words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      dictionary = Dictionary.find(params[:dictionary_id])
      @word = dictionary.words.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :language, :word_class, :definition, :comments, :frequency, :dictionary_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/dictionaries/_form.html.haml
= form_for @dictionary do |f|
  - if @dictionary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dictionary.errors.count, "error")} prohibited this dictionary from being saved:"
      %ul
        - @dictionary.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :language
    = f.text_field :language
  .actions
    = f.submit 'Save'

app/views/dictionaries/edit.html.haml
%h1 Editing dictionary

= render 'form'

= link_to 'Show', @dictionary
\|
= link_to 'Back', dictionaries_path

app/views/dictionaries/index.html.haml
%h1 Listing dictionaries

%table
  %thead
    %tr
      %th Name
      %th Language
      %th
      %th
      %th

  %tbody
    - @dictionaries.each do |dictionary|
      %tr
        %td= dictionary.name
        %td= dictionary.language
        %td= link_to 'Show', dictionary
        %td= link_to 'Edit', edit_dictionary_path(dictionary)
        %td= link_to 'Destroy', dictionary, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dictionary', new_dictionary_path

app/views/dictionaries/new.html.haml
%h1 New dictionary

= render 'form'

= link_to 'Back', dictionaries_path

app/views/dictionaries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @dictionary.name
%p
  %b Language:
  = @dictionary.language

= link_to 'Words', dictionary_words_path(@dictionary)
\|
= link_to 'Edit', edit_dictionary_path(@dictionary)
\|
= link_to 'Back', dictionaries_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Vocabapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/words/_form.html.haml
= form_for([@word.dictionary, @word]) do |f|
  - if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :language
    = f.text_field :language
  .field
    = f.label :word_class
    = f.text_field :word_class
  .field
    = f.label :definition
    = f.text_area :definition
  .field
    = f.label :comments
    = f.text_area :comments
  .field
    = f.label :frequency
    = f.number_field :frequency
  -#.field
    -# debugger
    -#= f.label :dictionary
    -#= f.text_field :dictionary
  %h3= "Dictionary: #{@word.dictionary.name}"
  .actions
    = f.submit 'Save'

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', [@word.dictionary, @word]
\|
= link_to 'Back', dictionary_words_path(@word.dictionary)

app/views/words/index.html.haml
%h1 Listing words

%table
  %thead
    %tr
      %th Name
      %th Language
      %th Word class
      %th Definition
      %th Comments
      %th Frequency
      %th Dictionary
      %th
      %th
      %th

  %tbody
    - @words.each do |word|
      %tr
        %td= word.name
        %td= word.language
        %td= word.word_class
        %td= word.definition
        %td= word.comments
        %td= word.frequency
        %td= word.dictionary.name
        %td= link_to 'Show', [word.dictionary, word]
        %td= link_to 'Edit', edit_dictionary_word_path(word.dictionary, word)
        %td= link_to 'Destroy', [word.dictionary, word], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Word', new_dictionary_word_path

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', dictionary_words_path(@word.dictionary)

app/views/words/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @word.name
%p
  %b Language:
  = @word.language
%p
  %b Word class:
  = @word.word_class
%p
  %b Definition:
  = @word.definition
%p
  %b Comments:
  = @word.comments
%p
  %b Frequency:
  = @word.frequency
%p
  %b Dictionary:
  = @word.dictionary.name

= link_to 'Edit', edit_dictionary_word_path(@word.dictionary, @word)
\|
= link_to 'Back', dictionary_words_path(@word.dictionary)